runs-on: ubuntu-latest
steps:
- name: Install SSH key
  uses: shimataro/ssh-key-action@v2
  with:
    key: ${{ secrets.SSH_PRIVATE_KEY }}
    known_hosts: unnecessary
    name: id_rsa # optional
    if_key_exists: fail # replace / ignore / fail; optional (defaults to fail)
- name: Adding Known Hosts
    run: ssh-keyscan -H ${{ secrets.SERVER_IP }} >> ~/.ssh/known_hosts
- name: Deploy with rsync
  run: rsync -avz /landing/ ${{ secrets.SSH_USER }}@${{ secrets.SERVER_IP }}:{{ secrets.ROUTE_APP }}